name: Recru-web

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Installing Node.js'

  - script: |
      npm install
      npm run build:prod
    displayName: 'Running npm install and build for prod'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)/dist'
      contents: |
        **/*
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      overWrite: true
    displayName: 'Copying built static files'

  - task: PublishBuildArtifacts@1
    displayName: 'Publishing Artifacts'